site:
  title: Documentation for ownCloud (A Kiteworks Company)
  url: https://doc.owncloud.com
  # the site's landing page resides in the docs_main repository/component
  # but it MUST be named ROOT to get a component/version less than the  landing page
  # this now makes the landing page reside in the url given above WITHOUT getting redirected
  # see: https://docs.antora.org/antora/latest/page/start-page/
  # see: https://docs.antora.org/antora/latest/component-name-key/#root-component
  start_page: ROOT::index.adoc

# define all content sources
# note that branches must already exist if changed here
content:
  sources:
  - url: https://github.com/owncloud/docs-main.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-server.git
    branches:
    - master
    - '10.14'
    - '10.13'
  - url: https://github.com/owncloud/docs-ocis.git
    branches:
    - master
    - '5.0'
    - '4.0'
  - url: https://github.com/owncloud/docs-webui.git
    branches:
    - master
  - url: https://github.com/owncloud/docs-client-desktop.git
    branches:
    - master
    - '5.2'
    - '5.1'
  - url: https://github.com/owncloud/docs-client-ios-app.git
    branches:
    - master
    - '12.1'
    - '12.0'
  - url: https://github.com/owncloud/docs-client-android.git
    branches:
    - master
    - '4.2'
    - '4.1'
  - url: https://github.com/owncloud/docs-client-branding.git
    branches:
    - master

ui:
  supplemental_files: overlay
  output_dir: assets
  bundle:
    snapshot: true
    url: https://minio.owncloud.com/documentation/ui-bundle.zip

output:
  clean: true
  dir: public

asciidoc:
  attributes:
#   branch-specific-variables: 'see antora.yml'
#   build relevant
    # asciidoctor prefix for section IDs
    idprefix: ''
    idseparator: '-'
    # Antora User Interface Macros (btn, menu)
    experimental: true
    # Antora pagination (prev page, next page)
    page-pagination: true
    # Custom attribute page-component-build-list
    # Only embed named opengraph images in docs-ui via src/partials/head-meta-opengraph.hbs sourced from docs/overlay
    page-component-build-list: 'docs, docs-main, ocis, server, webui, desktop, android, ios-app, branding'
#   common
    docs-base-url: 'https://doc.owncloud.com'
    oc-complete-base-url: 'https://download.owncloud.com/server/stable'
    oc-contact-url: 'https://owncloud.com/contact/'
    oc-help-url: 'https://owncloud.com/docs-guides/'
    oc-marketplace-url: 'https://marketplace.owncloud.com'
    oc-central-url: 'https://central.owncloud.org'
    oc-support-url: 'https://owncloud.com/support'
#
# note that all attributes ending with '@' are used for versioned docs. the content can be
# overwritten by the build process from the corresponding antory.yml file if populated - do not change
#
#   docs
    latest-docs-version: 'next'
    previous-docs-version: 'next'
#   server
    latest-server-version: '10.14'
    latest-server-download-version: '10.14.0'
    previous-server-version: '10.13'
    current-server-version: '10.14'
    oc-changelog-url: 'https://owncloud.com/changelog/server/'
    oc-install-package-url: 'https://download.owncloud.com/server/stable/?sort=time&order=asc'
    oc-examples-server-url: 'https://owncloud.install.com/owncloud'
    oc-examples-server-ip: '127.0.0.1'
    oc-examples-username: 'username'
    oc-examples-password: 'password'
    oc-complete-name: 'owncloud-complete-latest'
    occ-command-example-prefix: 'sudo -u www-data ./occ'
    occ-command-example-prefix-no-sudo: 'occ'
    php-net-url: 'https://www.php.net'
    php-supported-versions-url: 'https://www.php.net/supported-versions.php'
    http-status-codes-base-url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Status'
    std-port-http: '8080'
    std-port-memcache: '11211'
    std-port-mysql: '3306'
    std-port-redis: '6379'
#   ocis
    latest-ocis-version: '5.0'
    previous-ocis-version: '4.0'
    # These versions are just for printing, like in releases, but not used for referencing,
    # needs to be changed here and not in the docs-ocis repo to be properly shown on the web.
    # The following versions get printed on <all> build versions where applicable.
    # For branch-dependent version-specific content, change the values in antora.yml at compose_tab_1_tab_text.
    ocis-actual-version: '5.0.0'
    ocis-former-version: '4.0.7'
    ocis-compiled: '2024-03-18 00:00:00 +0000 UTC'
    ocis-downloadpage-url: 'https://download.owncloud.com/ocis/ocis/stable/'
#   webui
    latest-webui-version: 'next'
    previous-webui-version: 'next'
#   desktop
    latest-desktop-version: '5.2'
    previous-desktop-version: '5.1'
#   ios-app
    latest-ios-version: '12.1'
    previous-ios-version: '12.0'
#   android
    latest-android-version: '4.2'
    previous-android-version: '4.1'
#   branded
    latest-branded-version: 'next'
    previous-branded-version: 'next'
  extensions:
    - ./ext-asciidoc/tabs.js
    - ./ext-asciidoc/remote-include-processor.js
    - asciidoctor-kroki

antora:
  extensions:
    - ./ext-antora/generate-index.js
    - ./ext-antora/comp-version.js
    # for testing only, prints out attributes used
    # use only one or the other 
    #- ./ext-antora/attributes-used-in-site-yml.js
    #- ./ext-antora/attributes-used-in-antora-yml.js
